### ISSUE TITLE
API returns Error but page is still created

### ISSUE THREAD

**Issue by linusrogge** [k-next/kirby#6692]
## Description
When using the API route `/api/pages/:id/children` to create a page, the API returns an error **even though** the page is still created.

**Using localhost**
```json
{
    "status": "error",
    "message": "http://localhost:8000/panel/pages/entries+example",
    "code": 302,
    "exception": "Kirby\\Panel\\Redirect",
    "key": null,
    "file": "/kirby/src/Panel/Panel.php",
    "line": 149,
    "details": [],
    "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)/children"
}
```

**Using live site**
```json
{
    "status": "error",
    "message": "https://archive.saman.design/panel/pages/entries+example",
    "code": 302,
    "key": null,
    "details": []
}
```

**Expected behavior**  
The API should respond with a success message, using a code between 200 and 299

## To reproduce

1. Use the API at `/api/pages/:id/children` (eg. with Postman) to POST a new page with basic data
2. See Panel, page should be created
3. Request should return an error `302` response

## Your setup
**Kirby Version**  
Tried using both `v4.4.0` and `v4.3.1` (due to redirect errors mentioned in #6676).

**Your system (please complete the following information)**
 - Device: MacBook
 - OS: MacOS 15.0
 - Browser: Chrome

**Comment by linusrogge** [comment]
In addition to this, finding the API documentation on getkirby.com was a little bit of work.

I wanted to get to https://getkirby.com/docs/reference/api/pages/children-create, but clicking on `API → Pages` in the Reference sidebar leads me to https://getkirby.com/docs/reference/objects/cms/api/pages instead. Managed to get to the page via search, after all.

This also seems to be an issue with `API → Site` and `API → Users`.

**Comment by distantnative** [comment]
Thanks for reporting this. I have already fixed the API reference links.

**Comment by linusrogge** [comment]
Something I just remembered, that I did not include in the initial issue description: the site with this error uses a `page.create:after` hook to move items that were created within a category to a different parent (`entries`) where all of them are stored an instead referenced by the category UUID in the content.

In other words, this error is not directly related to the API, but does occur when using the API for pages that are affected because of the `entry` template. 

```php
'page.create:after' => function (Page $page) {
    if ($page->template() == 'entry') {
      if ($newPage->parent() != page('page://entries')) {
        if ($newPage->parent()->template()->name() == 'category') {
          $newPage->update([
            'category' => Yaml::encode([$newPage->parent()->uuid()->toString()])
          ]);
        }

        $newPage->move(page('page://entries'));
      }

      Panel::go('pages/entries+' . $newPage->slug());
    }
  }
```

The reason I am using this hook is to allow entries to be created in category panel pages (say `/panel/pages/architecture`), even though they should all eventually be store as children of `/panel/pages/entries`. In my mind, it made more sense to only have to query `page('entries')->children()` instead of the more heavy `$site->index()->filterBy('template', 'article')`, as this is a site with well over 1000 pages. Is this a valid concern or should I nest the children within their category folders and get rid of this code altogether?

**Comment by distantnative** [comment]
@linusrogge You are making a call to `$newPage->update()` which will create a new object (as objects are immutable in Kirby). But you don't continue using the newly created object, but make another call to `$newPage->move()`. Maybe this is the cause of your issues. Please try to actually continue with the returned object from `$newPage->update()`.

**Comment by linusrogge** [comment]
@distantnative Thanks for the hint. I adjusted the code to store the `$newPage->update()` in a new variable and then update the `move()` function as well. However, this did not solve the issue and I’m starting to think that it is because of the `Panel::go()` that is called. It is needed for when the pages are created from the Panel and not the API—then I want to route the user to the moved page, but I fear this is called also via the API and thus returns the 302 HTTP code.

I’m not sure how to go about this. Is there any way to check if `$kirby` inside this hook is accessed from the Panel vs. API or so?

**Comment by bastianallgeier** [comment]
Yes, it's indeed the Panel::go method. A hook should always be able to run as a simple task that has no additional side effects on routing or other parts of the system. There's no good way to make sure that this is only running in the right context.
